[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "py-qte"
version = "0.1.0"
description = "Quantile Treatment Effects"
authors = [
    { name = "Moritz Helm", email = "mohelm84@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.1",
    "polars>=1.43.2",
    "scipy>=1.18.0",
]

[dependency-groups]
dev = [
    "hatchling>=1.31.0",
    "pytest>=9.1.1",
    "ruff>=0.16.1",
    "ty>=0.0.66",
]
dev-helpers = [
    "ipython>=9.16.1",
]

[tool.hatch.build.targets.wheel]
packages = ["qte"]

